feat: sentry integration

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -11,7 +11,7 @@ inputs:
     default: "npm ci"
   build:
     description: "Set to true when the adapter needs a build step"
-    default: "false"
+    default: false
   build-command:
     description: "Overwrite the default build command"
     default: "npm run build"
@@ -21,6 +21,31 @@ inputs:
   github-token:
     description: "The token to use to create a GitHub release"
     required: true
+
+  sentry:
+    description: "Enable Sentry releases integration"
+    default: false
+  sentry-token:
+    description: "The token to use to create a Sentry release"
+    default: false
+  sentry-url:
+    description: "Under which URL the Sentry instance is running"
+    default: "https://sentry.iobroker.net"
+  sentry-org:
+    description: "Which Sentry organization the project is under"
+    default: "iobroker"
+  sentry-project:
+    description: "The project name on Sentry"
+    default: false
+  sentry-version-prefix:
+    description: "The prefix for release versions on Sentry"
+    default: false
+  sentry-github-integration:
+    description: "Set to true once Github integration is set up in Sentry"
+    default: false
+  sentry-sourcemap-paths:
+    description: "If sourcemaps should be uploaded to Sentry, specify their path here"
+    default: false
 
 # Conditional syntax isn't supported, but there are workarounds:
 # https://github.com/actions/runner/issues/834#issuecomment-909921245
@@ -83,4 +108,42 @@ runs:
         prerelease: ${{ contains(steps.extract_release.outputs.VERSION, '-') }}
         body: ${{ steps.extract_release.outputs.BODY }}
 
-    # TODO: Sentry
+    - name: Create Sentry release
+      shell: bash
+      run: |
+        if ! ${{ inputs.sentry }}; then
+          echo "Sentry release disabled..."
+          exit 0
+        fi
+
+        if ! ${{ inputs.sentry-token }}; then
+          echo "::error::Required input sentry-token not provided!"
+          exit 1
+        fi
+        if ! ${{ inputs.sentry-project }} ; then
+          echo "::error::Required input sentry-project not provided!"
+          exit 1
+        fi
+        if ! ${{ inputs.sentry-version-prefix }}; then
+          echo "::error::Required input sentry-version-prefix not provided!"
+          exit 1
+        fi
+
+        npm i -g @sentry/cli
+
+        export SENTRY_AUTH_TOKEN=${{ inputs.sentry-token }}
+        export SENTRY_URL=${{ inputs.sentry-url }}
+        export SENTRY_ORG=${{ inputs.sentry-org }}
+        export SENTRY_PROJECT=${{ inputs.sentry-project }}
+        export SENTRY_VERSION=${{ inputs.sentry-version-prefix }}@${{ steps.extract_release.outputs.VERSION }}
+        sentry-cli releases new $SENTRY_VERSION
+
+        if ${{ inputs.sentry-github-integration }}; then
+          sentry-cli releases set-commits $SENTRY_VERSION --auto
+        fi
+
+        if [[ "${{ inputs.sentry-sourcemap-paths }}" != "false" ]] ; then
+          sentry-cli releases files $SENTRY_VERSION upload-sourcemaps ${{ inputs.sentry-sourcemap-paths }}
+        fi
+
+        sentry-cli releases finalize $SENTRY_VERSION
